#!/usr/bin/env bash
# 1. World wide web

#!/usr/bin/env bash
# displays information about subdomains

print_subdomain ()
{
    output1line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tr '\n' ' ')
    echo "$2 $output1line" | awk '{print "The subdomain " $1 " is a " $8 " record and points to " $9}'
}

if [ "$#" -eq 1 ]; then
    for subdomain in "lb-01" "web-01" "web-02" "www"
    do
	print_subdomain "$1" "$subdomain"
    done
else
    print_subdomain "$1" "$2"
fi
