#!/usr/bin/env bash
# Bash script that configures HAproxy

apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0

apt-get update
apt-get install haproxy=2.0.\*

echo "
ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "
frontend haproxynode
    bind *:80
    mode http
    default_backend web-servers
backend web-backend
        balance roundrobin
        server 638-web-01 35.237.156.23:80 check
        server 638-web-02 35.185.70.190:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
