#!/usr/bin/env bash
# Bash script that configures HAproxy

apt-get install -y software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0

apt-get -y update
apt-get install -y haproxy=2.0.\*
echo "ENABLED=1" >> /etc/default/haproxy
echo "
frontend haproxynode
    bind *:80
    mode http
    default_backend web-servers
backend web-servers
        balance roundrobin
        server 638-web-01 35.237.156.23 check
        server 638-web-02 35.185.70.190 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
