#!/usr/bin/env bash
# Bash script that configures lb-01 HAproxy

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*
sed -i "$ a frontend load_balancer\n    bind *:80\n    mode http\n    default_backend web_servers\nbackend web_servers\n    balance roundrobin\n    server server1 34.74.113.114:80 check\n    server server2 34.74.5.236:80 check" /etc/haproxy/haproxy.cfg
# ufw allow 80/tcp
service haproxy start
