#!/usr/bin/env bash
# displays Holberton School 10 times

counter=1

while [ $counter -le 10 ]
do
  echo Holberton School
    if [ $counter = 9 ]
    then
        echo Hi
    fi
    ((counter++))
done
