#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

hr=0

while [ $hr -lt 13 ]
do
    echo "Hour: $hr"
    min=1
    while [ $min -lt 60 ]
    do
        echo $min
        ((min+=1))
    done
    ((hr+=1))
done
