#!/usr/bin/env bash
# change localhost and Facebook address
cp /etc/host ~/host.new
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
sed "$ a\8.8.8.8   facebook.com" ~/host.new
cp -f ~/hosts.new /etc/hosts
